@echo off
echo Starting UrbanMind Backend...
cd /d "%~dp0\.."
cd backend
echo Installing Python dependencies...
pip install -r requirements.txt
echo Starting FastAPI server...
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000